name: .NET

on:
  push:
  pull_request:
    branches: [ default ]

jobs:
  build-nix:
    name: build ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v2.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Windows and Linux buildscript
      run: ./.github/scripts/build-nix.sh
      env:
        INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE_9 }}
    - name: set s3 destination_dir
      run: echo "CURRENT_S3_DESTINATION=$CI_REPOSITORY_OWNER/$CI_REPOSITORY_NAME/$CI_REF_NAME_SLUG/$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Upload file to bucket
      uses: shallwefootball/s3-upload-action@v1.1.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: ./installers
        destination_dir: ${{ env.CURRENT_S3_DESTINATION }}
  build-mac:
    name: build macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v2.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: install create-dmg to bundle the app into a dmg
      run: brew install create-dmg
    - name: MacOS buildscript
      run: ./.github/scripts/build-mac.sh
    - name: set s3 destination_dir
      run: echo "CURRENT_S3_DESTINATION=$CI_REPOSITORY_OWNER/$CI_REPOSITORY_NAME/$CI_REF_NAME_SLUG/$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Upload file to bucket
      uses: shallwefootball/s3-upload-action@v1.1.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: ./dmg
        destination_dir: ${{ env.CURRENT_S3_DESTINATION }}
  build-win:
    name: build windows installer with innosetup
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v2.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: win buildscript
      run: ./.github/scripts/build-win.bat
    - name: set s3 destination_dir
      run: echo "CURRENT_S3_DESTINATION=$CI_REPOSITORY_OWNER/$CI_REPOSITORY_NAME/$CI_REF_NAME_SLUG/$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      shell: bash
    - name: Upload file to bucket
      uses: WycliffeAssociates/upload-s3-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: ./Output
        destination_dir: ${{ env.CURRENT_S3_DESTINATION }}

