name: .NET

on:
  push:
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: build win
      run: dotnet publish ./USFMConverter/USFMConverter.sln -c Release --self-contained true -o ./output -r win-x64
    - name: build linux
      run: dotnet publish ./USFMConverter/USFMConverter.sln -c Release --self-contained true -o ./output -r linux-x64
    - name: build mac
      run: dotnet publish ./USFMConverter/USFMConverter.sln -c Release --self-contained true -o ./output -r osx-x64
