name: .NET

on:
  push:
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v2.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: build win
      run: dotnet publish ./USFMConverter/USFMConverter.sln -c Release --self-contained true -o ./output -r win-x64
#    - name: build linux
#     run: dotnet publish ./USFMConverter/USFMConverter.sln -c Release --self-contained true -o ./output -r linux-x64
#    - name: build mac
#      run: dotnet publish ./USFMConverter/USFMConverter.sln -c Release --self-contained true -o ./output -r osx-x64
    - name: set s3 destination_dir
      run: echo "CURRENT_S3_DESTINATION=$CI_REPOSITORY_OWNER/$CI_REPOSITORY_NAME/$CI_REF_NAME_SLUG/$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Upload file to bucket
      uses: shallwefootball/s3-upload-action@v1.1.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: ./output-nix
        destination_dir: ${{ env.CURRENT_S3_DESTINATION }}/output-nix
